#3. Fibonacci Sequence
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

n1 = 0
n2 = 1
n0 = n1 + n2
sums = 0

while n0 <= 4000000:
    n0 = n1 + n2
    n1 = n2
    n2 = n0
    if n1 % 2 == 0:
        sums += n1 
print(sums)

